bigquery:
  outputs:
    prod:
      type: bigquery
      dataset: "{% raw %}{{ env_var('DBT_SCHEMA', 'dwh') }}{% endraw %}"
      project: "{% raw %}{{ env_var('DBT_DATABASE', 'geller') }}{% endraw %}"
      keyfile: "{% raw %}{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', 'sa.json') }}{% endraw %}"
      location: EU
      method: service-account
      priority: interactive
      threads: 16
      timeout_seconds: 300
      fixed_retries: 1
  target: prod